/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DashboardStats = IDL.Record({
  'delayed' : IDL.Nat,
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'totalProjects' : IDL.Nat,
  'totalSpent' : IDL.Float64,
  'totalBudget' : IDL.Float64,
  'onTrack' : IDL.Nat,
});
export const DocumentFolder = IDL.Variant({
  'Contract' : IDL.Null,
  'Study' : IDL.Null,
  'Execution' : IDL.Null,
  'Correspondence' : IDL.Null,
});
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'docNumber' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'projectId' : IDL.Nat,
  'folder' : DocumentFolder,
  'fileUrl' : IDL.Text,
});
export const FinancialItem = IDL.Record({
  'id' : IDL.Nat,
  'allocated' : IDL.Float64,
  'spent' : IDL.Float64,
  'projectId' : IDL.Nat,
  'category' : IDL.Text,
});
export const ObstacleStatus = IDL.Variant({
  'Open' : IDL.Null,
  'InProgress' : IDL.Null,
  'Resolved' : IDL.Null,
});
export const ObstaclePriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Obstacle = IDL.Record({
  'id' : IDL.Nat,
  'status' : ObstacleStatus,
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
  'priority' : ObstaclePriority,
});
export const ProjectStatus = IDL.Variant({
  'OnTrack' : IDL.Null,
  'Delayed' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'endDate' : IDL.Text,
  'projectType' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'totalCost' : IDL.Float64,
  'spent' : IDL.Float64,
  'progress' : IDL.Nat,
  'location' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'plannedEnd' : IDL.Text,
  'assignee' : IDL.Text,
  'name' : IDL.Text,
  'projectId' : IDL.Nat,
  'plannedStart' : IDL.Text,
  'actualEnd' : IDL.Opt(IDL.Text),
  'actualStart' : IDL.Opt(IDL.Text),
});
export const ReportData = IDL.Record({
  'projectsByStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'projectsByYear' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'financialSummary' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64)),
  'projectsByLocation' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});

export const idlService = IDL.Service({
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
  'getFinancialItems' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FinancialItem)],
      ['query'],
    ),
  'getObstacles' : IDL.Func([IDL.Nat], [IDL.Vec(Obstacle)], ['query']),
  'getProjectById' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjectTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getReportData' : IDL.Func([], [ReportData], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DashboardStats = IDL.Record({
    'delayed' : IDL.Nat,
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'totalProjects' : IDL.Nat,
    'totalSpent' : IDL.Float64,
    'totalBudget' : IDL.Float64,
    'onTrack' : IDL.Nat,
  });
  const DocumentFolder = IDL.Variant({
    'Contract' : IDL.Null,
    'Study' : IDL.Null,
    'Execution' : IDL.Null,
    'Correspondence' : IDL.Null,
  });
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'docNumber' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'projectId' : IDL.Nat,
    'folder' : DocumentFolder,
    'fileUrl' : IDL.Text,
  });
  const FinancialItem = IDL.Record({
    'id' : IDL.Nat,
    'allocated' : IDL.Float64,
    'spent' : IDL.Float64,
    'projectId' : IDL.Nat,
    'category' : IDL.Text,
  });
  const ObstacleStatus = IDL.Variant({
    'Open' : IDL.Null,
    'InProgress' : IDL.Null,
    'Resolved' : IDL.Null,
  });
  const ObstaclePriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Obstacle = IDL.Record({
    'id' : IDL.Nat,
    'status' : ObstacleStatus,
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
    'priority' : ObstaclePriority,
  });
  const ProjectStatus = IDL.Variant({
    'OnTrack' : IDL.Null,
    'Delayed' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'endDate' : IDL.Text,
    'projectType' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'totalCost' : IDL.Float64,
    'spent' : IDL.Float64,
    'progress' : IDL.Nat,
    'location' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'plannedEnd' : IDL.Text,
    'assignee' : IDL.Text,
    'name' : IDL.Text,
    'projectId' : IDL.Nat,
    'plannedStart' : IDL.Text,
    'actualEnd' : IDL.Opt(IDL.Text),
    'actualStart' : IDL.Opt(IDL.Text),
  });
  const ReportData = IDL.Record({
    'projectsByStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'projectsByYear' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'financialSummary' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64)),
    'projectsByLocation' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  
  return IDL.Service({
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
    'getFinancialItems' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FinancialItem)],
        ['query'],
      ),
    'getObstacles' : IDL.Func([IDL.Nat], [IDL.Vec(Obstacle)], ['query']),
    'getProjectById' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjectTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getReportData' : IDL.Func([], [ReportData], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };