/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'delayed' : bigint,
  'pending' : bigint,
  'completed' : bigint,
  'totalProjects' : bigint,
  'totalSpent' : number,
  'totalBudget' : number,
  'onTrack' : bigint,
}
export interface Document {
  'id' : bigint,
  'docNumber' : string,
  'date' : string,
  'name' : string,
  'projectId' : bigint,
  'folder' : DocumentFolder,
  'fileUrl' : string,
}
export type DocumentFolder = { 'Contract' : null } |
  { 'Study' : null } |
  { 'Execution' : null } |
  { 'Correspondence' : null };
export interface FinancialItem {
  'id' : bigint,
  'allocated' : number,
  'spent' : number,
  'projectId' : bigint,
  'category' : string,
}
export interface Obstacle {
  'id' : bigint,
  'status' : ObstacleStatus,
  'description' : string,
  'projectId' : bigint,
  'priority' : ObstaclePriority,
}
export type ObstaclePriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type ObstacleStatus = { 'Open' : null } |
  { 'InProgress' : null } |
  { 'Resolved' : null };
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'endDate' : string,
  'projectType' : string,
  'name' : string,
  'year' : bigint,
  'totalCost' : number,
  'spent' : number,
  'progress' : bigint,
  'location' : string,
  'startDate' : string,
}
export type ProjectStatus = { 'OnTrack' : null } |
  { 'Delayed' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface ReportData {
  'projectsByStatus' : Array<[string, bigint]>,
  'projectsByYear' : Array<[bigint, bigint]>,
  'financialSummary' : Array<[string, number, number]>,
  'projectsByLocation' : Array<[string, bigint]>,
}
export interface Task {
  'id' : bigint,
  'plannedEnd' : string,
  'assignee' : string,
  'name' : string,
  'projectId' : bigint,
  'plannedStart' : string,
  'actualEnd' : [] | [string],
  'actualStart' : [] | [string],
}
export interface _SERVICE {
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDocuments' : ActorMethod<[bigint], Array<Document>>,
  'getFinancialItems' : ActorMethod<[bigint], Array<FinancialItem>>,
  'getObstacles' : ActorMethod<[bigint], Array<Obstacle>>,
  'getProjectById' : ActorMethod<[bigint], [] | [Project]>,
  'getProjectTasks' : ActorMethod<[bigint], Array<Task>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getReportData' : ActorMethod<[], ReportData>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];