/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ReportData {
    projectsByStatus: Array<[string, bigint]>;
    projectsByYear: Array<[bigint, bigint]>;
    financialSummary: Array<[string, number, number]>;
    projectsByLocation: Array<[string, bigint]>;
}
export interface Obstacle {
    id: bigint;
    status: ObstacleStatus;
    description: string;
    projectId: bigint;
    priority: ObstaclePriority;
}
export interface FinancialItem {
    id: bigint;
    allocated: number;
    spent: number;
    projectId: bigint;
    category: string;
}
export interface Task {
    id: bigint;
    plannedEnd: string;
    assignee: string;
    name: string;
    projectId: bigint;
    plannedStart: string;
    actualEnd?: string;
    actualStart?: string;
}
export interface Document {
    id: bigint;
    docNumber: string;
    date: string;
    name: string;
    projectId: bigint;
    folder: DocumentFolder;
    fileUrl: string;
}
export interface Project {
    id: bigint;
    status: ProjectStatus;
    endDate: string;
    projectType: string;
    name: string;
    year: bigint;
    totalCost: number;
    spent: number;
    progress: bigint;
    location: string;
    startDate: string;
}
export interface DashboardStats {
    delayed: bigint;
    pending: bigint;
    completed: bigint;
    totalProjects: bigint;
    totalSpent: number;
    totalBudget: number;
    onTrack: bigint;
}
export enum DocumentFolder {
    Contract = "Contract",
    Study = "Study",
    Execution = "Execution",
    Correspondence = "Correspondence"
}
export enum ObstaclePriority {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum ObstacleStatus {
    Open = "Open",
    InProgress = "InProgress",
    Resolved = "Resolved"
}
export enum ProjectStatus {
    OnTrack = "OnTrack",
    Delayed = "Delayed",
    Completed = "Completed",
    Pending = "Pending"
}
export interface backendInterface {
    getDashboardStats(): Promise<DashboardStats>;
    getDocuments(projectId: bigint): Promise<Array<Document>>;
    getFinancialItems(projectId: bigint): Promise<Array<FinancialItem>>;
    getObstacles(projectId: bigint): Promise<Array<Obstacle>>;
    getProjectById(id: bigint): Promise<Project | null>;
    getProjectTasks(projectId: bigint): Promise<Array<Task>>;
    getProjects(): Promise<Array<Project>>;
    getReportData(): Promise<ReportData>;
}
import type { Document as _Document, DocumentFolder as _DocumentFolder, Obstacle as _Obstacle, ObstaclePriority as _ObstaclePriority, ObstacleStatus as _ObstacleStatus, Project as _Project, ProjectStatus as _ProjectStatus, Task as _Task } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDocuments(arg0: bigint): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocuments(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocuments(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialItems(arg0: bigint): Promise<Array<FinancialItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialItems(arg0);
            return result;
        }
    }
    async getObstacles(arg0: bigint): Promise<Array<Obstacle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getObstacles(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObstacles(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectById(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectById(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectById(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectTasks(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectTasks(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectTasks(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportData(): Promise<ReportData> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportData();
            return result;
        }
    }
}
function from_candid_DocumentFolder_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentFolder): DocumentFolder {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Document_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ObstaclePriority_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ObstaclePriority): ObstaclePriority {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ObstacleStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ObstacleStatus): ObstacleStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Obstacle_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Obstacle): Obstacle {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProjectStatus;
    endDate: string;
    projectType: string;
    name: string;
    year: bigint;
    totalCost: number;
    spent: number;
    progress: bigint;
    location: string;
    startDate: string;
}): {
    id: bigint;
    status: ProjectStatus;
    endDate: string;
    projectType: string;
    name: string;
    year: bigint;
    totalCost: number;
    spent: number;
    progress: bigint;
    location: string;
    startDate: string;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n16(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        projectType: value.projectType,
        name: value.name,
        year: value.year,
        totalCost: value.totalCost,
        spent: value.spent,
        progress: value.progress,
        location: value.location,
        startDate: value.startDate
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    plannedEnd: string;
    assignee: string;
    name: string;
    projectId: bigint;
    plannedStart: string;
    actualEnd: [] | [string];
    actualStart: [] | [string];
}): {
    id: bigint;
    plannedEnd: string;
    assignee: string;
    name: string;
    projectId: bigint;
    plannedStart: string;
    actualEnd?: string;
    actualStart?: string;
} {
    return {
        id: value.id,
        plannedEnd: value.plannedEnd,
        assignee: value.assignee,
        name: value.name,
        projectId: value.projectId,
        plannedStart: value.plannedStart,
        actualEnd: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.actualEnd)),
        actualStart: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.actualStart))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    docNumber: string;
    date: string;
    name: string;
    projectId: bigint;
    folder: _DocumentFolder;
    fileUrl: string;
}): {
    id: bigint;
    docNumber: string;
    date: string;
    name: string;
    projectId: bigint;
    folder: DocumentFolder;
    fileUrl: string;
} {
    return {
        id: value.id,
        docNumber: value.docNumber,
        date: value.date,
        name: value.name,
        projectId: value.projectId,
        folder: from_candid_DocumentFolder_n4(_uploadFile, _downloadFile, value.folder),
        fileUrl: value.fileUrl
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ObstacleStatus;
    description: string;
    projectId: bigint;
    priority: _ObstaclePriority;
}): {
    id: bigint;
    status: ObstacleStatus;
    description: string;
    projectId: bigint;
    priority: ObstaclePriority;
} {
    return {
        id: value.id,
        status: from_candid_ObstacleStatus_n9(_uploadFile, _downloadFile, value.status),
        description: value.description,
        projectId: value.projectId,
        priority: from_candid_ObstaclePriority_n11(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    InProgress: null;
} | {
    Resolved: null;
}): ObstacleStatus {
    return "Open" in value ? ObstacleStatus.Open : "InProgress" in value ? ObstacleStatus.InProgress : "Resolved" in value ? ObstacleStatus.Resolved : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): ObstaclePriority {
    return "Low" in value ? ObstaclePriority.Low : "High" in value ? ObstaclePriority.High : "Medium" in value ? ObstaclePriority.Medium : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OnTrack: null;
} | {
    Delayed: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): ProjectStatus {
    return "OnTrack" in value ? ProjectStatus.OnTrack : "Delayed" in value ? ProjectStatus.Delayed : "Completed" in value ? ProjectStatus.Completed : "Pending" in value ? ProjectStatus.Pending : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Contract: null;
} | {
    Study: null;
} | {
    Execution: null;
} | {
    Correspondence: null;
}): DocumentFolder {
    return "Contract" in value ? DocumentFolder.Contract : "Study" in value ? DocumentFolder.Study : "Execution" in value ? DocumentFolder.Execution : "Correspondence" in value ? DocumentFolder.Correspondence : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Obstacle>): Array<Obstacle> {
    return value.map((x)=>from_candid_Obstacle_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
